### ISSUE TITLE
Towns in extracts

### ISSUE THREAD

**Issue by klokan** [geometalab/OSMNames#12]
Adust docker workflow (source code in this repo) and include towns and assignment of towns to a country (parsing from places and first hierarchical import).

Run it on planet dump extract of Switzerland - and deliver exported .csv as part of the milestone release.

This is the essential step to make a progress with this project, should not be delayed. It was discussed on April 25th.

Would be good to have alpha version during this week (latest till Friday?). The result should be delivered and presented latest on milestone meeting (Monday 16:00) on Skype.

@and01 could you please provide progress report here?

**Comment by and01** [comment]
already on it, will try to meet the Friday deadline for alpha version..

**Comment by klokan** [comment]
Cool! I am glad to hear the project is not stalled. Look forward to hearing from you!

**Comment by and01** [comment]
I have done the mapping with a planet dump of Switzerland. Took less than 10 minutes for the whole process. The following fields are in the exported tsv as of now:

- name
- class
- type
- lon
- lat
- place_rank (same as in nominatim)
- importance (calculated from place_rank)
- display_name (hierarchy like in nominatim, or close to it)
- west
- south
- east
- north

check https://github.com/geometalab/OSMNames/blob/master/data/cities.tsv

As of now I have 2914 entries for the town extract. After analyzing the dataset a bit I realized that node villages are missing altogether. I have to adapt the imposm mapping for that. I get back to you..

**Comment by and01** [comment]
Alright. Datafile updated with nodes import.. Now it looks more complete with 12485 entries too many though. Still lots of duplicates to be handled.

Side note: Google Spreadsheet seems to handle UTF-8 encoding in tsv a lot better than my excel does.

**Comment by klokan** [comment]
Great! I am glad to see there nice results! Thanks @and01
