### ISSUE TITLE
Handling street geometries as aggregates

### ISSUE THREAD

**Issue by sfkeller** [geometalab/OSMNames#13]
(engl. translation to follow): Oft sind in OSM eigentlich zusammengehörende Strassen (mit gleichem Namen) gestückelt, wie z.B. die Spitalstrassse hier: http://www.openstreetmap.org/search?query=Spitalstrasse%2070%20Wetzikon#map=15/47.3249/8.8135 . Nominatim z.B. behandelt das als 4 unabhängige Strassen wenn die Hausnummer nicht vorhanden ist. D.h. die (nicht existierende Hausnr. 70) wird nicht in die Mitte der Strasse gesetzt... Solche zusammengehörenden Strassen sollten eigentlich für Geocoding-Zwecke zu Multi-Linestrings aufgearbeitet werden.

**Comment by lukasmartinelli** [comment]
We face the same problem in osm2vectortiles when setting road labels. Would be cool to see an approach to aggregate them in into one Linestring.

**Comment by klokan** [comment]
An example of this problem is #22

**Comment by and01** [comment]
As for how the street segments are getting merged:

1. find all linestrings that share the same parent_id and name
2. if the geometries of those touch each other it is considered to be the same street and therefore getting merged as a MultiLinestring
