### ISSUE TITLE
add language support

### ISSUE THREAD

**Issue by and01** [geometalab/OSMNames#16]
currently the exported tsv includes all languages. This results in a long display_name. E.g.
`Erschwil, Bezirk Thierstein, Amtei Dorneck-Thierstein, Solothurn, Schweiz, Suisse, Svizzera, Svizra`
Therefore it would be swell to have a language based export.

**Comment by and01** [comment]
Tried to import all the name tags with the `hstore_tags` of imposm. Unfortunately this doesn't work. Workaround is to import only predefined languages, one column for each. 
@lukasmartinelli Have you found a better solution?

**Comment by lukasmartinelli** [comment]
> Tried to import all the name tags with the hstore_tags of imposm.

Should work with `hstore` tags. Perhaps forgot the `tags` YAML definition at the top of the YAML file?

```yaml
tags:
  load_all: true,
  exclude: [created_by, source, "tiger:*"]
```

**Comment by and01** [comment]
turns out, that only predefined languages are meant to be supported. hstore_tags in imposm puts all the tags in one hstore column which is not preferable anyway.
