### ISSUE TITLE
get rid of duplicates

### ISSUE THREAD

**Issue by and01** [geometalab/OSMNames#17]
In the current dataset of v0.2 there a still some duplicates. The reason is that sometimes the name in the same for the village and the administrative boundary. Add some logic the prevent. E.g. if administrative available take this entry and delete the other one, as the boundaries are more precise.
Example:
`Erstfeld	boundary	administrative	8.600908996	46.81278292	16	0.35	Erstfeld, Uri, Schweiz, Suisse, Svizzera, Svizra	8.517504723	46.77636908	8.683019567	46.84932148`
and
`Erstfeld	place	village	8.64996352	46.82150873	19	0.275	Erstfeld, Uri, Schweiz, Suisse, Svizzera, Svizra	8.64996352	46.82150873	8.64996352	46.82150873`

**Comment by klokan** [comment]
Bern example - point + boundary of city vs boundary of state:
http://nominatim.openstreetmap.org/search.php?q=bern&polygon=1&viewbox=
