### ISSUE TITLE
Nominatim Analysis

### ISSUE THREAD

**Issue by and01** [geometalab/OSMNames#2]
- install nominatim
- find out how the importing process and ranking process works in detail

**Comment by klokan** [comment]
@and01 - any progress on this? Can you please write a short report of status?
What have you achieved so far?

**Comment by klokan** [comment]
While playing with Nominatim installation and your local instance - it would be really great to focus on understanding two areas:
- Hierarchy reconstruction process (#5)
- Ranking process (#4)

**Comment by and01** [comment]
@klokan Sorry for keeping you waiting which I was not aware of. I will get back to you asap when I have results regarding #4 and #5

**Comment by and01** [comment]
- I have a running nominatim installation and imported a small dataset (Luxembourg).
- I have done an analysis on #4 and #5 .
- What I didn't do is wikipedia import which apparently takes a lot of time but is relevant for the importance.

**Comment by klokan** [comment]
@and01 used docker https://github.com/nicopace/nominatim-docker for tests

**Comment by klokan** [comment]
Closing. Basic tests done for today's meeting. Thank you Andreas!
