### ISSUE TITLE
extend export and hierarchy calculation up to street level

### ISSUE THREAD

**Issue by and01** [geometalab/OSMNames#20]

**Comment by klokan** [comment]
Status of v0.3 release?

**Comment by and01** [comment]
sorry for the delay

**Comment by klokan** [comment]
BTW latest v0.3 data deployed and searchable at http://osmnames.klokantech.com/.

Details at https://github.com/klokantech/osmnames-sphinxsearch in tickets.
Looking forward to 0.4 with improved importance and ranking and with the world coverage.

**Comment by and01** [comment]
very nice. thx
