### ISSUE TITLE
Wikipedia importance

### ISSUE THREAD

**Issue by klokan** [geometalab/OSMNames#21]
Importing Wikipedia into a Postgres database and improve the calculation of importance based on these data.

To be done with a separate Dockerfile included in the importing process.

Based on #4

**Comment by and01** [comment]
separate docker compose or as part of the import-osm compose?

**Comment by klokan** [comment]
Separate Dockerfile.

I still hope in minimal changes in the original code from OSM2VectorTIles, so we may be able to keep the two projects synchronised together - not forked completely.

**Comment by klokan** [comment]
Cool! Could you please update README.md?
IMHO "import-wikipedia" is a better name then "import-wp".

I am keen to know if the wikipedia article name "URL part of wikipedia) is available in the database and could be possibly exported. This is interesting for use of OSMNames data dumps in the LinkedData environment, where the wikipedia URL is used as unique identifier.

**Comment by and01** [comment]
URL part not available ATM, but can be done if needed

**Comment by klokan** [comment]
+1
