### ISSUE TITLE
Duplicates for same street with different bounding box

### ISSUE THREAD

**Issue by MartinMikita** [geometalab/OSMNames#22]
For example: http://osmnames.klokantech.com/search?q=hoffnerstrasse+unterageri&format=html

**Comment by klokan** [comment]
Is the 0.4 going to be released soon, @and01?

**Comment by and01** [comment]
@klokan Yes. Just a few refactorings and the processing of Europe dump away. Probably tomorrow.

**Comment by and01** [comment]
As for how the street segments are getting merged:

1. find all linestrings that share the same parent_id and name
2. if the geometries of those touch each other it is considered to be the same street and therefore getting merged as a MultiLinestring
