### ISSUE TITLE
Data format of hierarchical geonames

### ISSUE THREAD

**Issue by klokan** [geometalab/OSMNames#3]
Target of the project is to have data export extremely easy to use with any fulltext search engine or SQL database.

Best praxis meeting this criteria is in GeoNames.org project - with .tsv format defined at: http://download.geonames.org/export/dump/

and GISGraphy:
http://download.gisgraphy.com/format.txt

My initial suggestion for the format is:
```
*osm_id - MUST BE UNIQUE "DOCUMENT ID" accross complete database

display_name - exactly as in Nominatim (may be improved later)

*name (=utf-8)
name_en
name_de
name_es
name_fr
name_ru
name_zh

*class
*type

*north (=boundingbox)
*south
*east
*west

*lat
*lon

scalerank - we have it
place_rank - nominatim has it

importance - exactly as in nominatim calculated

country (=country code, ISO-3166 2-letter country code)

street=<housenumber> <streetname>
city=<city>
county=<county>
state=<state>
country=<country>
postalcode=<postalcode>

(= a la nominatim http://wiki.openstreetmap.org/wiki/Nominatim)

? timestamp - osm modification?
```

This is mostly derived from JSON provided by Nominatim - see: http://wiki.openstreetmap.org/wiki/Nominatim and  
http://nominatim.klokantech.com/?q=paris&format=jsonv2&addressdetails=1
and from the fields we have already in vector tiles in OSM2VectorTiles project.

On this ticket we should agree on the details of the export data format.

**Comment by klokan** [comment]
Comments from @sfkeller:

* Don't forget geom of type polygon.
* osm_id is only (sowehow) unique in within OSM entities Node,Way,Relation. So Node 240025182 must have a prefix (which would make it char(11) according to http://www.w3schools.com/sql/sql_datatypes.asp).
* The role of fields class and type is not clear to me: Can you give me examples?
* Field names place_rank and importance must be more self describing
* Field street is not clear to me: Either drop it (since it belongs to building address) - and if we keep it, split it into fields street and house_number.
* In Toponyms there are rather "place" than street. 
* Rename timestamp to last_modified

I'm going to write a schema definition.

**Comment by klokan** [comment]
My answers:

- Polygon GEOMs are usually not required for gazeteers and make the export significantly larger. Some of the polygons can be huge! In general I am not against adding them into the export format - but maybe we can separate these information into a different file? How to serialise them?
Best practice in project: http://download.gisgraphy.com/openstreetmap/

- `osm_id` is unique in OSM2VectorTIles - see "OSM IDs" paragraph in https://www.mapbox.com/developers/vector-tiles/mapbox-streets-v6/

- `class` and `type` exist already in OSM2VectorTiles vector tiles. No change on this for OSMNames - the mapping of the OSM tags is already done.

- `place_rank` and `importance` - the field names are derived from existing Nominatim JSON reponse. Details of the ranking to be discussed under #4

- `street` and `house_number` fields are directly derived from Nominatim JSON response: http://nominatim.klokantech.com/?q=paris&format=jsonv2&addressdetails=1
Hopefully as part of analyse #2 we get know more about why is it this way in Nominatim

- timestamp field may be only internal - for the purpose of diff generation and future updates (a filename may define a time of the diff instead)

**Comment by sfkeller** [comment]
Thanks for reaorganizing.

1. I would simplify the polygons. For use cases other than "zoom to" they are important (take Chili, Norway, Sumatra where their bbox covers dozens of other countries). External representation can be GeoJSON (binary representation is hidden by the SW). Or did I misunderstand your serialization question?
2. osm_id: Clever mapbox-streets def. which hopefully holds some time as OSM ids get larger and larger. Note that osm_id has a different def. in the canonical SW osm2pgsql.
3. My question is what is the role of class and type in context of a gazeteer?
4. Ok.
5. I assumed that street and house_number fields are from Nominatim. But what's the use case here? House_numbers usually don't belong to gazeteers and are definitely a info to be separated from streets.
6. Ok.

**Comment by klokan** [comment]
1. What is your typical use-case for polygons with generalisation in a gazetteer? With vector tiles you can highlight polygon with known osm_id after a result of search - the visible map on screen is always square. To avoid issues of bounding box for a strange shape Google Gazetteer API has distinguish bounding box and view box (which would be a reasonable request to add here instead of polygon). Serialisation may be GeoJSON (easy to use but huge) or something like HEXEWKB.

3. Distinguishing in results or filtering queries on types or classes. Nominatim itself has it in JSON. It is practicaly to be able to query the server only for specific types or classes - or filter the results on client side.

5. Technically not strictly required for typical use case. Use case is again filtering - queries like "all house numbers on given street" or "all streets in given town" or "all towns having a street with this name".

**Comment by sfkeller** [comment]
* 1 The generic use case is to do a "is obj. contained-by gazetteer name?" query. Vector tiles are nifty but should not be a prerequisite for using OSMNames. Regarding serialization I assumed this is about a data exchange format here. But I'm not against HEXEWKB (little-endian).

* 3 Ok.

* 5 There are several non-technical and technical reasons to avoid streets and house numbers here. Non-technical reason is that people would expect OSMNames to be a postal address database (it's important to me that users realize that this gazetteer is NOT made for address geocoding). In a geonames model house numbers are really not part of the street. To me both, streets and house numbers have to be kept separated from geographic names.

**Comment by klokan** [comment]
We follow for now the proposed tsv format
