### ISSUE TITLE
provide export for World

### ISSUE THREAD

**Issue by and01** [geometalab/OSMNames#30]

**Comment by and01** [comment]
processing times as follows:

- import 20h
- export 8h
TOTAL of 28 hours for planet dump

**Comment by and01** [comment]
file here:
https://github.com/geometalab/OSMNames/releases/download/v1.0/planet-latest.tsv.gz

**Comment by klokan** [comment]
Cool! Thank you a lot.

We are going to update the search engine and report you the status...
