### ISSUE TITLE
Invalid lines in data version 0.6 (Europe)

### ISSUE THREAD

**Issue by MartinMikita** [geometalab/OSMNames#32]
Input file has 8 478 324 entries (without first header line).
Sphinxsearch has processed 8 478 284 entries.

40 lines are invalid: number of columns isn't 19, some column values are missing.

See attached tsv, ods and xls files packed in ZIP.

[europe-invalid.zip](https://github.com/geometalab/OSMNames/files/366369/europe-invalid.zip)

**Comment by and01** [comment]
@MartinMikita Thx for providing the faulty data. I will take a closer look at how I can avoid these entries..

**Comment by klokan** [comment]
This is now deprecated ticket - the invalid lines for world contains invalid lines for Europe as well.
#36
