### ISSUE TITLE
Duplicate of same results?

### ISSUE THREAD

**Issue by MartinMikita** [geometalab/OSMNames#33]
I have found duplicate of same entry:
http://osmnames.klokantech.com/?q=humenne+presov&format=html

Entry line 2876052 and 2876053

```
Humenné	boundary	administrative	21.90590524496128	48.94311364081	18	0.3		okres Humenné	" "	Prešovský kraj	Slovakia	sk	Humenné, okres Humenné, Prešovský kraj, Východné Slovensko	21.85670398275343	48.906349733391124	21.952359183778924	48.97980253019544	" "
Humenné	boundary	administrative	21.90590524496128	48.94311364081	20	0.25		okres Humenné	" "	Prešovský kraj	Slovakia	sk	Humenné, okres Humenné, Prešovský kraj, Východné Slovensko	21.85670398275343	48.906349733391124	21.952359183778924	48.97980253019544	" "
```

**Comment by and01** [comment]
True. In the osm data there are two geometries as well, also with different ranks. See
https://nominatim.openstreetmap.org/details.php?place_id=145024048
and
https://nominatim.openstreetmap.org/details.php?place_id=144733756
For now I just mark nodes that correspond to a polygon, so we don't have them twice in there. The question is whether to pre-process equal geometries and to pick just one of them (which?) to use further on..

**Comment by MartinMikita** [comment]
another same entry, with little change in lon/lat:
http://osmnames.klokantech.com/?q=golden+gate+bridge&format=html

**Comment by klokan** [comment]
This is exactly the same problem of reported "class" and "type" as in #35 

Request to Nominatim: http://nominatim.openstreetmap.org/?q=humenne+presov&format=json
returns one of the first three records with class: `place` and type: `town`.
OSMNames returns only administrative boundaries - and no town type.
