### ISSUE TITLE
OSM or place_id identifier

### ISSUE THREAD

**Issue by klokan** [geometalab/OSMNames#34]
It seems we have completely lost the OSM id on the way to export...

It would be great to have it included in the export - so the links like https://nominatim.openstreetmap.org/details.php?place_id=145024048
can be constructed automatically, such as mentioned in #33.

We have three options for format:
- Native OSM identifier (with prefix for node/way/relation)
- Encoded with older transition MapBox (OSM2VT V1): see OSM-ID at https://www.mapbox.com/vector-tiles/mapbox-streets-v5/
- Encoded a la Imposm3 (and vector tiles in OSM2VT V2 with `use_single_id_space: true`):  https://github.com/osm2vectortiles/osm2vectortiles/issues/281

This is primarily for linking back to OSM objects for more info, and for debugging purposes.
Nominatim provides the the IDs too - and is doing almost equal operation as our code.

What do you think about this @and01?

**Comment by and01** [comment]
Currently only osm_id of type _imposm_ are imported (negative for relations). So this could added to the export easily. However, there arises a problem when exporting merged linestrings which consists of multiple osm_ids. A solution could be to have an array of the according osm_id(s).

Btw: the place_id of nominatim as seen in the URLs in #33 corresponds to the place_id in table placex which is the primary key and has nothing to do with the osm_id.

**Comment by klokan** [comment]
OK. Postponed.

**Comment by klokan** [comment]
Is the `place_id` unique (=there are not equal place_ids in the dump) and permanent (new import produce for the same place the same place_id - equal to nominatim place_id)?

If this is true - I suggest to add it to the export.

**Comment by klokan** [comment]
@and01 please comment

**Comment by and01** [comment]
`place_id` is nominatim specific and not reproducible. Also, it is equal osm features do not have same place_ids in different nominatim instances.  I will additionally export native OSM identifiers and their respective types..

**Comment by and01** [comment]
For your reference: Check the different place_ids for same features:
http://nominatim.klokantech.com/?q=humenne+presov&format=json
https://nominatim.openstreetmap.org/?q=humenne+presov&format=json

**Comment by klokan** [comment]
The decision is include two new columns with values like:
```
osm_type: "relation",
osm_id: "7444",
```
We follow the Nominatim implementation in this.
Example query: 
http://nominatim.openstreetmap.org/?q=paris&format=json

**Comment by klokan** [comment]
Thanks. Just a notice, the debugging links are going to look like:
http://www.openstreetmap.org/relation/7444
http://www.openstreetmap.org/way/27403881
http://www.openstreetmap.org/node/4290439927
