### ISSUE TITLE
Cities reported as administrative boundaries

### ISSUE THREAD

**Issue by klokan** [geometalab/OSMNames#35]
When searching for "Paris" at:
http://nominatim.openstreetmap.org/search.php?q=paris&polygon=1&viewbox=
the first two records are reported by Nominatim as "City" and "County".

The same search on OSMNames:
http://osmnames.klokantech.com/?q=paris&format=html
returns both records - but both are "adminstrative boundaries".

Isn't this caused by merging the bounding box record to the city record?

The two records should be distinguishable. What can be done to improve the type reported - so people can choose between two different records (city and county) instead of between two equal records?

Probably related to #33

**Comment by and01** [comment]
There is no merging of administrative boundaries. These two entries for Paris both of type boundary:administrative also exist in nominatim. However, the place_rank 16 suggests city whereas place_rank 12 corresponds to county. I am sure the appropriate column 'county' and 'city' are set appropriately.

**Comment by klokan** [comment]
User should be presented with option "Paris [city]" and "Paris [administrative unit]". This is not possible with OSMNames data now - as both records are reported as type administrative boundary.

Nominatim query like http://nominatim.openstreetmap.org/?q=paris&format=json contains:
```js
[{
    place_id: "2617072610",
    osm_type: "relation",
    osm_id: "7444",
    boundingbox: [
        "48.8155755",
        "48.902156",
        "2.224122",
        "2.4697602"
    ],
    lat: "48.8566101",
    lon: "2.3514992",
    display_name: "Paris, Ile-de-France, Metropolitan France, France",
    class: "place", -----------------------------------------
    type: "city",   -----------------------------------------
    importance: 0.96893459932191,
}, {
    place_id: "143540975",
    osm_type: "relation",
    osm_id: "71525",
    boundingbox: [
        "48.8155755",
        "48.902156",
        "2.224122",
        "2.4697602"
    ],
    lat: "48.85881005",
    lon: "2.32003101155031",
    display_name: "Paris, Ile-de-France, Metropolitan France, France",
    class: "boundary", -----------------------------------------
    type: "administrative", -----------------------------------------
    importance: 0.96893459932191,
},
...
```

The first record has the class:`place` and type:`city`.
OSMNames should have the same class and type for the first record.

I think this is a bug.

**Comment by and01** [comment]
Do I understand correctly, you want both records in there, place as well as administrative?
https://nominatim.openstreetmap.org/?q=Ketintang&format=jsonv2 delivers both and OSMNames only delivers the administrative one. This is because currently the place entry gets marked as linked to the administrative one, maybe wrongfully and therefore not being in the dataset.

**Comment by and01** [comment]
As for Paris: The relation in question with id 7444 is the following:
https://www.openstreetmap.org/relation/7444
https://nominatim.openstreetmap.org/details.php?place_id=2617072610
The type is administrative/boundary. I correctly link the node
https://www.openstreetmap.org/node/17807753
and therefore doesn't show in the export, because it is the relation's `admin_center`.

What you want is to change the type of 7444 to the ones of the node 17807753, right?

**Comment by klokan** [comment]
In general - our target is to have exactly the same what is in Nominatim JSON - done the way it is done in Nominatim.

How do they put it the "city" type?

**Comment by and01** [comment]
After countless hours of analyzing data and code I finally cracked it: The type of relations change to place:city when the following conditions are given:

- the relation has a linked osm node
- the relation has a place_rank of 16 (city)
- the relation is of type 'administrative'
- the type of the linked node is 'city'

Nominatim shows this state with the following symbol in the search results (you have to know it!!):
https://nominatim.openstreetmap.org/images/mapicons/poi_place_city.p.20.png

**Comment by klokan** [comment]
Really cool! Thank you a lot @and01. Great job.

Do you have a link to the source code in Nominatim - where is visible what you wrote above? Is it done at the moment of query or during update of the database?

**Comment by and01** [comment]
It's done during the export query. I can also move that to the import step.
