### ISSUE TITLE
Invalid lines in data version 1.0 (World/Planet)

### ISSUE THREAD

**Issue by MartinMikita** [geometalab/OSMNames#36]
Input file has 20 842 915 entries (without first header line).
Sphinxsearch has processed 20 735 819 entries.

107 096 lines are invalid: number of columns isn't 19, some column values are missing.

10 lines contains field values with tab (this is not acceptable, and cannot be fixed with pre-processing):
```
1529261-\t-"Avenida -\t-A el Cargadero"-\t-primary-\t-primary-\t--102.99770443241843-\t-22.65882699820638-\t-26-\t-0.09999999999999998-\t-"Avenida -\t-A el Cargadero"-\t-" "-\t-Jerez-\t-Zacatecas-\t-Mexico-\t-mx-\t-"Avenida -\t-A el Cargadero, Jerez, Zacatecas, Mexico"-\t--102.99841050106902-\t-22.657710165970382-\t--102.99699831802235-\t-22.659943859347116-\t-" "
```

See attached tsv, ods and xls files packed in ZIP
[planet-invalid-lines.zip](https://github.com/geometalab/OSMNames/files/371432/planet-invalid-lines.zip)

BTW command for checking:
`cat data.tsv | sed -e 's/\r/ /g' | awk -F"\t" 'NR > 1 && NF != 19 {print NR"\t"$0}' > data-invalid-lines.tsv`

**Comment by and01** [comment]
Thx a lot @MartinMikita for formulating the command above. This will help a lot solving the problem..

**Comment by and01** [comment]
- tabs in names are getting eliminated
- missing country names caused empty country codes fields
- some lost islands belong to their respective countries once again ;-)

Result should be visible with next export dump by next week..
