### ISSUE TITLE
Export of native & alternative names

### ISSUE THREAD

**Issue by klokan** [geometalab/OSMNames#37]
For sure it would be good to export the native name of places (name_en vs name as in vector tiles).

Now native name like "Praha" is not discovered. In other scripts (such as japan, china, thai, etc) the original names are undiscoverable.

GeoNames has a single "alternativenames" record.

To be discussed on Monday @and01

**Comment by klokan** [comment]
"alternative_names" should contain every alternative name of a place, but the one already visible in the "name" column - all separted by comma. This is for fulltext search to be able to discover place names like "Praha".

Please make a note here about how to switch the name and display_name generator into anther language (such as german) - so people can run their own export with a different native language they preffer.

**Comment by and01** [comment]
The language precedence can be interchanged in the function getLanguageName in src/export-osmnames/functions.sql. Currently its set in the following order

1.  en
2. default
3. fr
4. de
5. es
6. ru
7. zh

**Comment by cbocionek** [comment]
I have changed the language precedence in getLanguageName() in order to export German names, yet the exported names are in English.

**Comment by klokan** [comment]
It may be that the getLanguageName() order influence the order of languages inside of the "alternative_names" field export discussed in this ticket, but does not ensure your primary language for "name" field export will switch to "de" / German...

This is a closed ticket. Create a new ticket and describe clearly what you want to do, please.
