### ISSUE TITLE
Export shorter Wikipedia + Wikidata ID

### ISSUE THREAD

**Issue by klokan** [geometalab/OSMNames#42]
Nominatim returns wikipedia link in a short variant such as "es:Buenos Aires".
It would be better to return in OSMNames this short variant too - not a complete URL.

Another helpful information in the export would be wikidata id (such as "Q23436").

In Nominatim JSON these are columns "wikipedia" and "wikidata".

Merging via the relation "label" may be required - as mentioned in #41 and #35

**Comment by and01** [comment]
So I export it as I have it in the DB, just the short variant like: "en:Paris, Missouri".
I can include wikidata id as well if you really want to.

**Comment by klokan** [comment]
Cool. +1
