### ISSUE TITLE
Export made for release 1.1

### ISSUE THREAD

**Issue by klokan** [geometalab/OSMNames#43]
We are ready to make an update of the osmnames.klokantech.com, but the release is not yet made.

What is the status of export made for the release 1.1?

**Comment by and01** [comment]
@klokan Sorry about that. I found another bug last week and after re-running the process I was away and therefore not able to upload the file. Releasing in a couple of minutes..

**Comment by klokan** [comment]
Thanks! Now everything in the code is fixed - so we can easily regenerate the data, if required?

**Comment by and01** [comment]
Yes you can. Although I was having problems with the latest planet pbf dump having invalid geometries. I will try to fix that during this week. The focus from now on will be on documentation. BTW thx for the template.
