### ISSUE TITLE
Imposm3 import test

### ISSUE THREAD

**Issue by klokan** [geometalab/OSMNames#7]
Check documentation of OSM2VectorTiles:
http://osm2vectortiles.org/docs/ (section Import and Export).

and dockers for import* at:
https://github.com/osm2vectortiles/osm2vectortiles/tree/master/src

Try to extend existing imposm3 import process with a new table for reconstructing the hierarchy similar to Nominatim's OSM2PGSQL #6

**Comment by klokan** [comment]
May be helpful: http://imposm.org/docs/imposm3/latest/relations.html

**Comment by klokan** [comment]
Report?

On Wednesday, 13 April 2016, Stefan <notifications@github.com> wrote:

> Closed #7 <https://github.com/geometalab/OSMNames/issues/7>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/geometalab/OSMNames/issues/7#event-625533303>
>


-- 
Petr Pridal, Ph.D.
CEO

Klokan Technologies GmbH
Hofnerstrasse 98, 6314 Unterageri, Switzerland
Tel: +41 (0)41 511 26 12
Email: info@klokantech.com
Web: http://www.klokantech.com/

**Comment by and01** [comment]
Got somehow closed..
